<?php

namespace App\Controller\Admin;

use App\Controller\Admin\AppController;
use Cake\Datasource\ConnectionManager;
use Authentication\IdentityInterface;
use Cake\ORM\Entity;

/**
 * TbDiversidadCultivos Controller
 *
 * @property \App\Model\Table\TbDiversidadCultivosTable $TbDiversidadCultivos
 *
 * @method \App\Model\Entity\TbDiversidadCultivos[] paginate($object = null, array $settings = [])
 */
class TbDiversidadCultivosController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_title = "agrobiodiversidad de cultivo";
        $this->loadModel('Zabd');
        $this->loadModel('TbVariedades');
        $this->loadModel('TbConocimientoEmpleado');
        $this->loadModel('OptionList');
        $this->loadModel('TbCultivo');
        // $this->loadModel('TbCultivoConocimiento');
        $this->loadModel('TbComunidad');
        $this->loadModel('TbCentroPoblado');

        $this->loadModel('TbParientesSilvestres');
        // $this->loadModel('TbEtapaConocimiento');
        $this->loadModel('TbNombresComunes');
        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' => 'Zabd'])->first();
        if (!empty($this->module))
            $this->permiso = $this->Functions->validarModulo($this->module->id);
        $this->mod_modulo = "zona de agrobiodiversidad";
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */

    public function index($idx = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['index']) {
            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $permiso = $this->permiso;
            $styles = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
            $scripts = [
                'assets/js/select2/select2',
                'assets/js/datatable/jquery.dataTables.min',
                'assets/js/datatable/dataTables.bootstrap.min',
                'assets/js/datatable/dataTables.select.min'
            ];
            $TbDiversidadCultivos = $this->TbDiversidadCultivos->find()->contain(['TbCentroPoblado', 'TbCultivo', 'TbVariedades', 'TbParientesSilvestres', 'TbNombresComunes', 'TbNombresCientificos', 'TbFamilias', 'Zabd'])->where(['tb_zabd_id' => $Zabd->id, 'TbDiversidadCultivos.status' => 1])->all();
            if ($TbDiversidadCultivos != NULL) {

                $this->set(compact('TbDiversidadCultivos', 'Zabd', 'mod_modulo', 'mod_title', 'styles', 'scripts', 'permiso'));
                $this->set('_serialize', ['TbDiversidadCultivos']);
            } else {

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'Zabd']);
            }
        } else {

            $this->Flash->error(__('No tiene permisos.'));
            return $this->redirect(['action' => 'index', 'controller' => 'Zabd']);
        }
    }

    /**
     * View method
     *
     * @param string|null $id Zabd Accesion id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($idx = null, $id = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['view']) {
            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $permiso = $this->permiso;
            $TbDiversidadCultivos = $this->TbDiversidadCultivos->find()->contain(['TbCentroPoblado', 'TbCultivo', 'TbVariedades', 'TbParientesSilvestres', 'TbNombresComunes', 'TbNombresCientificos', 'TbFamilias', 'Zabd'])
                ->where(['TbDiversidadCultivos.id' => $id, 'TbDiversidadCultivos.tb_zabd_id' => $idx, 'TbDiversidadCultivos.status' => '1'])
                ->first();

            if ($TbDiversidadCultivos != NULL) {
                $this->set(compact('TbDiversidadCultivos', 'mod_modulo', 'mod_title', 'permiso', 'Zabd'));
                $this->set('_serialize', ['TbDiversidadCultivos']);
            } else {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'TbDiversidadCultivos', $idx]);
            }
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbDiversidadCultivos', $idx]);
        }
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($idx = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['add']) {
            $TbDiversidadCultivos = $this->TbDiversidadCultivos->newEntity();
            if ($this->request->is('post')) {
                $data = $this->request->getData();
                $data['tb_zabd_id'] = $Zabd->id;
                $data['tb_tipo_diversidad_id'] = 1;
                $TbDiversidadCultivos = $this->TbDiversidadCultivos->patchEntity($TbDiversidadCultivos, $data);
                if ($this->TbDiversidadCultivos->save($TbDiversidadCultivos)) {
                    $list_module = explode('/', $this->request->params['_matchedRoute']);
                    $user_id = $this->Auth->User('id');
                    $module = $list_module[(count($list_module) - 2)];
                    $action = $list_module[(count($list_module) - 1)];
                    $station_id = $TbDiversidadCultivos->id;
                    $recurso_id = '4';
                    // Agregar a Conocimiento Empleado
                    // $cn = ConnectionManager::get('default');
                    // foreach ($data['tb_conocimiento_id'] as $idConocimiento) {
                    //     $query = "INSERT INTO tb_conocimiento_empleado (tb_conocimiento_tradicional_id , tb_conocimiento_id) VALUES ($TbDiversidadCultivos->id , $idConocimiento);";
                    //     $add_conocimiento = $cn->prepare($query);
                    //     $add_conocimiento->execute();
                    // }
                    // // Agresgar los cultivos
                    // foreach ($data['tb_cultivo_id'] as $idCultivo) {
                    //     $query = "INSERT INTO tb_cultivo_conocimiento (tb_conocimiento_tradicional_id , tb_cultivo_id) VALUES ($TbDiversidadCultivos->id , $idCultivo);";
                    //     $add_conocimiento = $cn->prepare($query);
                    //     $add_conocimiento->execute();
                    // }
                    // // Agresgar los etapas
                    // foreach ($data['tb_etapa_id'] as $idEtapa) {
                    //     $query = "INSERT INTO tb_etapa_conocimiento (tb_conocimiento_tradicional_id , tb_etapa_id) VALUES ($TbDiversidadCultivos->id , $idEtapa);";
                    //     $add_conocimiento = $cn->prepare($query);
                    //     $add_conocimiento->execute();
                    // }
                    // var_dump($data['tb_conocimiento_id']); exit();

                    // --
                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                    $this->Flash->success(__('Conocimiento tradicional creado satisfactoriamente.'));
                    return $this->redirect(['action' => 'index', 'idx' => $Zabd->id]);
                }
                $this->Flash->error(__('VERIFICAR QUE NO HAYA DUPLICIDAD.'));
            }
            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];

            
            $TbCultivo = $this->TbCultivo->find('list', ['keyField' => 'id', 'valueField' => 'cultivo'])->where(['TbCultivo.status' => 1]);
            $TbVariedades = $this->TbVariedades->find('list', ['keyFiled' => 'id', 'valueField' => 'variedad'])->where(['TbVariedades.status' => '1']);
            $TbParientesSilvestres = $this->TbDiversidadCultivos->TbParientesSilvestres->find('list', ['keyField' => 'id', 'valueField' => 'pariente_silvestre'])->where(['TbParientesSilvestres.status' => '1']);
            $TbCentroPoblado = $this->TbCentroPoblado->find('list', ['keyFiled' => 'id', 'valueField' => 'centro_poblado'])->contain(['TbComunidad'])->where(['TbCentroPoblado.status' => '1','TbComunidad.tb_zabd_id'=> $Zabd->id]);
            $TbNombresComunes = $this->TbNombresComunes->find('list', ['keyField' => 'id', 'valueField' => 'nombre_comun'])->where(['TbNombresComunes.status' => 1, 'TbNombresComunes.tb_tipo_diversidad_id'=>1]);
            $TbNombresCientificos = $this->TbDiversidadCultivos->TbNombresCientificos->find('list', ['keyFiled' => 'id', 'valueField' => 'nombre_cientifico'])->where(['TbNombresCientificos.status'=>1, 'TbNombresCientificos.tb_tipo_diversidad_id'=>1]);
            $TbFamilias = $this->TbDiversidadCultivos->TbFamilias->find('list', ['keyFiled' => 'id', 'valueField' => 'familia'])->where(['TbFamilias.status'=>1,'TbFamilias.tb_tipo_diversidad_id'=>1]);
            // var_dump($TbFamilias); exit;
            $this->set(compact('TbDiversidadCultivos', 'mod_modulo', 'mod_title', 'TbCentroPoblado', 'TbCultivo', 'TbVariedades', 'TbParientesSilvestres',  'TbNombresComunes',  'TbNombresCientificos', 'TbFamilias', 'Zabd'));
            $this->set('_serialize', ['TbDiversidadCultivos']);
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbDiversidadCultivos', $idx]);
        }
    }

    /**
     *
     * @param string|null $id Zabd Accesion id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($idx = null, $id = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        // $TbVariedades = $this->TbVariedades->find('list', ['keyFiled' => 'id', 'valueField' => 'variedad'])->where(['TbVariedades.status' => '1']);
        // $TbConocimientoEmpleado = $this->TbConocimientoEmpleado->find()->contain(['TbDiversidadCultivos', 'TbVariedades'])->where(['TbConocimientoEmpleado.tb_conocimiento_tradicional_id' => $id, 'TbConocimientoEmpleado.status' => '1'])->all();
        // $TbCultivoConocimiento = $this->TbCultivoConocimiento->find()->contain(['TbDiversidadCultivos', 'TbCultivo'])->where(['TbCultivoConocimiento.tb_conocimiento_tradicional_id' => $id, 'TbCultivoConocimiento.status' => '1'])->all();
        // $TbEtapaConocimiento = $this->TbEtapaConocimiento->find()->contain(['TbDiversidadCultivos', 'TbParientesSilvestres'])->where(['TbEtapaConocimiento.tb_conocimiento_tradicional_id' => $id, 'TbEtapaConocimiento.status' => '1'])->all();
        // foreach ($TbConocimientoEmpleado as $key => $value) {
        //     $conocimiento_id[] = ($value['tb_conocimiento']['id']);
        // }
        // foreach ($TbCultivoConocimiento as $key => $value) {
        //     $cultivo_id[] = ($value['tb_cultivo']['id']);
        // }
        // foreach ($TbEtapaConocimiento as $key => $value) {
        //     $etapa_id[] = ($value['tb_etapa']['id']);
        // }
        if ($Zabd != NULL && $this->permiso['add']) {
            $TbDiversidadCultivos = $this->TbDiversidadCultivos->find()->where(['TbDiversidadCultivos.id' => $id, 'TbDiversidadCultivos.status' => '1', 'tb_zabd_id' => $idx])->first();
            $TbParientesSilvestres = $this->TbDiversidadCultivos->TbParientesSilvestres->find('list', ['keyField' => 'id', 'valueField' => 'pariente_silvestre', 'limit' => 200]);
            if ($TbDiversidadCultivos != NULL) {
                if ($this->request->is(['patch', 'post', 'put'])) {
                    $data = $this->request->getData();
                    $data['tb_zabd_id'] = $Zabd->id;
                    $TbDiversidadCultivos = $this->TbDiversidadCultivos->patchEntity($TbDiversidadCultivos, $data);
                    if ($this->TbDiversidadCultivos->save($TbDiversidadCultivos)) {
                        $list_module = explode('/', $this->request->params['_matchedRoute']);
                        $user_id = $this->Auth->User('id');
                        $module = $list_module[(count($list_module) - 2)];
                        $action = $list_module[(count($list_module) - 1)];
                        $station_id = $TbDiversidadCultivos->id;
                        $recurso_id = '4';
                        // $cn = ConnectionManager::get('default');
                        // Agregar a Conocimiento Empleado
                        // $arrayConocimientoId = implode(',', $data['tb_conocimiento_id']);
                        // if ($data['tb_conocimiento_id']) {
                        //     $query = "CALL sp_update_conocimiento_empleado(" . $TbDiversidadCultivos->id . ",'$arrayConocimientoId');";
                        //     $add_conocimiento = $cn->prepare($query);
                        //     $add_conocimiento->execute();
                        //     foreach ($data['tb_conocimiento_id'] as $idConocimiento) {
                        //         if ($idConocimiento != $conocimiento_id) {
                        //             $query = "INSERT INTO tb_conocimiento_empleado (tb_conocimiento_tradicional_id , tb_conocimiento_id) VALUES ($TbDiversidadCultivos->id  , $idConocimiento);";
                        //             $add_conocimiento = $cn->prepare($query);
                        //             $add_conocimiento->execute();
                        //         }
                        //     }
                        // }
                        // // Agregar Cultivo_Conocimiento select2
                        // $arrayCultivoConocimientoId = implode(',', $data['tb_cultivo_id']);
                        // if ($data['tb_cultivo_id']) {
                        //     $query = "CALL sp_update_cultivo_conocimiento(" . $TbDiversidadCultivos->id . ",'$arrayCultivoConocimientoId');";
                        //     $add_conocimiento = $cn->prepare($query);
                        //     $add_conocimiento->execute();
                        //     foreach ($data['tb_cultivo_id'] as $idCultivoConocimiento) {
                        //         if ($idCultivoConocimiento != $cultivo_id) {
                        //             $query = "INSERT INTO tb_cultivo_conocimiento (tb_conocimiento_tradicional_id , tb_cultivo_id) VALUES ($TbDiversidadCultivos->id  , $idCultivoConocimiento);";
                        //             $add_conocimiento = $cn->prepare($query);
                        //             $add_conocimiento->execute();
                        //         }
                        //     }
                        // }
                        // // Agregar Etapa_Conocimiento select2
                        // if ($data['tb_etapa_id']) {
                        //     $Data = $data['tb_etapa_id'];
                        //     $arrayId = implode(',', $Data);
                        //     $query = "CALL sp_update_etapa_conocimiento(" . $TbDiversidadCultivos->id . ",'$arrayId');";
                        //     $excecute = $cn->prepare($query);
                        //     $excecute->execute();
                        //     foreach ($Data as $getId) {
                        //         if ($getId != $etapa_id) {
                        //             $query = "INSERT INTO tb_etapa_conocimiento (tb_conocimiento_tradicional_id , tb_etapa_id) VALUES ($TbDiversidadCultivos->id  , $getId);";
                        //             $excecute = $cn->prepare($query);
                        //             $excecute->execute();
                        //         }
                        //     }
                        // }
                        // --
                        $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                        $this->Flash->success(__('Conocimiento tradicional actualizado satisfactoriamente.'));
                        return $this->redirect(['action' => 'index', 'idx' => $Zabd->id]);
                    }
                    $this->Flash->error(__('VERIFICAR QUE NO HAYA DUPLICIDAD.'));
                }
                $mod_modulo = $this->mod_modulo;
                $mod_title = $this->mod_title;
                $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];

                $TbCultivo = $this->TbCultivo->find('list', ['keyField' => 'id', 'valueField' => 'cultivo'])->where(['TbCultivo.status' => 1]);
                $TbVariedades = $this->TbVariedades->find('list', ['keyFiled' => 'id', 'valueField' => 'variedad'])->where(['TbVariedades.status' => '1']);
                $TbParientesSilvestres = $this->TbDiversidadCultivos->TbParientesSilvestres->find('list', ['keyField' => 'id', 'valueField' => 'pariente_silvestre'])->where(['TbParientesSilvestres.status' => '1']);
                $TbCentroPoblado = $this->TbCentroPoblado->find('list', ['keyFiled' => 'id', 'valueField' => 'centro_poblado'])->contain(['TbComunidad'])->where(['TbCentroPoblado.status' => '1','TbComunidad.tb_zabd_id'=> $Zabd->id]);
                $TbNombresComunes = $this->TbNombresComunes->find('list', ['keyField' => 'id', 'valueField' => 'nombre_comun'])->where(['TbNombresComunes.status' => 1, 'TbNombresComunes.tb_tipo_diversidad_id'=>1]);
                $TbNombresCientificos = $this->TbDiversidadCultivos->TbNombresCientificos->find('list', ['keyFiled' => 'id', 'valueField' => 'nombre_cientifico'])->where(['TbNombresCientificos.status'=>1, 'TbNombresCientificos.tb_tipo_diversidad_id'=>1]);
                $TbFamilias = $this->TbDiversidadCultivos->TbFamilias->find('list', ['keyFiled' => 'id', 'valueField' => 'familia'])->where(['TbFamilias.status'=>1,'TbFamilias.tb_tipo_diversidad_id'=>1]);
    
                $this->set(compact('TbDiversidadCultivos', 'mod_modulo', 'mod_title', 'TbCentroPoblado', 'TbCultivo', 'TbVariedades', 'TbParientesSilvestres',  'TbNombresComunes',  'TbNombresCientificos', 'TbFamilias', 'Zabd'));
                $this->set('_serialize', ['TbDiversidadCultivos']);
            } else {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'TbDiversidadCultivos', $idx]);
            }
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbDiversidadCultivos', $idx]);
        }
    }

    /**
     * Delete method
     *
     * @param string|null $id Zabd Accesion id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($idx = null, $id = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['delete']) {
            $this->request->is(['post', 'delete']);
            $TbDiversidadCultivos = $this->TbDiversidadCultivos->find()->where(['TbDiversidadCultivos.id' => $id, 'TbDiversidadCultivos.status' => '1', 'tb_zabd_id' => $idx])->first();
            if ($TbDiversidadCultivos == NULL) {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'TbDiversidadCultivos', $idx]);
            } else {
                $TbDiversidadCultivos['status'] = 0;
                if ($this->TbDiversidadCultivos->save($TbDiversidadCultivos)) {
                    $list_module = explode('/', $this->request->params['_matchedRoute']);
                    $user_id = $this->Auth->User('id');
                    $module = $list_module[(count($list_module) - 3)];
                    $action = $list_module[(count($list_module) - 2)];
                    $station_id = $TbDiversidadCultivos->id;
                    $recurso_id = '4';
                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                    $this->Flash->success(__('Conocimiento tradicional eliminada satisfactoriamente.'));
                } else {
                    $this->Flash->error(__('Hubo inconvenientes al eliminar la Conocimiento tradicional. Por favor, otra vez intente.'));
                }
                return $this->redirect(['action' => 'index', 'idx' => $TbDiversidadCultivos->tb_zabd_id]);
            }
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbDiversidadCultivos', $idx]);
        }
    }

    public function exportartabla($idx = null)
    {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT . 'reportes/' . $data['filename'] . '.xlsx';

            if (file_exists($filePath)) {

                $this->response->file($filePath, array('download' => true));

                return $this->response;
            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }
}
