<?php
namespace App\Controller\Admin;

use App\Controller\Admin\AppController;
use Cake\Datasource\ConnectionManager;

/**
 * TbRecorrido Controller
 *
 * @property \App\Model\Table\TbRecorridoTable $TbRecorrido
 *
 * @method \App\Model\Entity\TbRecorrido[] paginate($object = null, array $settings = [])
 */
class TbRecorridoController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_modulo = "zona de agrobiodiversidad";
        $this->mod_title = "Accesibilidad";
        $this->loadModel('Zabd');
        $this->loadModel('OptionList');
        $this->loadModel('Passport');

        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' => 'Zabd'])->first();
        if (!empty($this->module))
            $this->permiso = $this->Functions->validarModulo($this->module->id);
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */

    public function index($idx = null)
    {

        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['index']) {
            
            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $permiso = $this->permiso;
            
            $styles = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
            $scripts = [
                'assets/js/select2/select2',
                'assets/js/datatable/jquery.dataTables.min',
                'assets/js/datatable/dataTables.bootstrap.min',
                'assets/js/datatable/dataTables.select.min'
            ];
            
            // faltaria agregar el status
            $TbRecorrido = $this->TbRecorrido->find()->contain(['Zabd'])->where(['tb_zabd_id' => $Zabd->id, 'TbRecorrido.status' => 1])->all();
            
            if ($TbRecorrido != NULL) {
                
                $this->set(compact('TbRecorrido', 'Zabd', 'mod_modulo', 'mod_title', 'styles', 'scripts', 'permiso'));
                $this->set('_serialize', ['TbRecorrido']);
                
            } else {
                
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'Zabd']);
            }

        } else {

            $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index', 'controller' => 'Zabd']);

        }
    }

    /**
     * View method
     *
     * @param string|null $id Zabd Accesion id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($idx = null, $id = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['view']) {
            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $permiso = $this->permiso;
            $TbRecorrido = $this->TbRecorrido->find()->contain([ 'Zabd'])
                ->where(['TbRecorrido.id' => $id, 'TbRecorrido.tb_zabd_id' => $idx, 'TbRecorrido.status' => '1'])
                ->first();
            if ($TbRecorrido != NULL) {
                $this->set(compact('TbRecorrido', 'mod_modulo', 'mod_title', 'permiso', 'Zabd'));
                $this->set('_serialize', ['TbRecorrido']);
            } else {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'TbRecorrido', $idx]);
            }
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbRecorrido', $idx]);
        }
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($idx = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        
        if ($Zabd != NULL && $this->permiso['add']) {
            $TbRecorrido = $this->TbRecorrido->newEntity();
            if ($this->request->is('post')) {
            // if (1==1) {
                $data = $this->request->getData();
                $data['tb_zabd_id'] = $Zabd->id;
                $TbRecorrido = $this->TbRecorrido->patchEntity($TbRecorrido, $data);
                if ($this->TbRecorrido->save($TbRecorrido)) {
                    $list_module = explode('/', $this->request->params['_matchedRoute']);
                    $user_id = $this->Auth->User('id');
                    $module = $list_module[(count($list_module) - 2)];
                    $action = $list_module[(count($list_module) - 1)];
                    $station_id = $TbRecorrido->id;
                    // var_dump($station_id); exit;
                    $recurso_id = '4';
                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                    $this->Flash->success(__('Accesibilidad creado satisfactoriamente.'));
                    return $this->redirect(['action' => 'index', 'idx' => $Zabd->id]);

                }
                $this->Flash->error(__('Hubo inconvenientes al crear la accesibilidad. Por favor, otra vez intente.'));
            }

            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];
            $this->set(compact('TbRecorrido', 'mod_modulo', 'mod_title','Zabd'));
            $this->set('_serialize', ['TbRecorrido']);
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbRecorrido', $idx]);
        }
    }

    /**
     *
     * @param string|null $id Zabd Accesion id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($idx = null, $id = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['add']) {
            $TbRecorrido = $this->TbRecorrido->find()->where(['TbRecorrido.id' => $id, 'TbRecorrido.status' => '1', 'tb_zabd_id' => $idx])->first();
            if ($TbRecorrido != NULL) {
                if ($this->request->is(['patch', 'post', 'put'])) {
                    // var_dump($TbRecorrido); exit; 
                    $data = $this->request->getData();
                    $data['tb_zabd_id'] = $Zabd->id;
                    $TbRecorrido = $this->TbRecorrido->patchEntity($TbRecorrido, $data);
                    if ($this->TbRecorrido->save($TbRecorrido)) {
                        $list_module = explode('/', $this->request->params['_matchedRoute']);
                        $user_id = $this->Auth->User('id');
                        $module = $list_module[(count($list_module) - 2)];
                        $action = $list_module[(count($list_module) - 1)];
                        $station_id = $TbRecorrido->id;
                        $recurso_id = '4';
                        $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                        $this->Flash->success(__('Accesibilidad Actualizado satisfactoriamente.'));
                        return $this->redirect(['action' => 'index', 'idx' => $Zabd->id]);
                    }
                    $this->Flash->error(__('Hubo inconvenientes al actualizar la accesibilidad. Por favor, otra vez intente.'));
                }
                $mod_modulo = $this->mod_modulo;
                $mod_title = $this->mod_title;
                $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];

                $this->set(compact('TbRecorrido', 'mod_modulo', 'mod_title', 'Zabd'));
                $this->set('_serialize', ['TbRecorrido']);
            } else {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'TbRecorrido', $idx]);
            }
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbRecorrido', $idx]);
        }
    }

    /**
     * Delete method
     *
     * @param string|null $id Zabd Accesion id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($idx = null, $id = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['delete']) {
            $this->request->is(['post', 'delete']);
            $TbRecorrido = $this->TbRecorrido->find()->where(['TbRecorrido.id' => $id, 'TbRecorrido.status' => '1', 'tb_zabd_id' => $idx])->first();
            if ($TbRecorrido == NULL) {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'TbRecorrido', $idx]);
            } else {
                $TbRecorrido['status'] = 0;
                if ($this->TbRecorrido->save($TbRecorrido)) {
                    $list_module = explode('/', $this->request->params['_matchedRoute']);
                    $user_id = $this->Auth->User('id');
                    $module = $list_module[(count($list_module) - 3)];
                    $action = $list_module[(count($list_module) - 2)];
                    $station_id = $TbRecorrido->id;
                    $recurso_id = '4';
                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                    $this->Flash->success(__('Accesibilidad eliminada satisfactoriamente.'));
                } else {
                    $this->Flash->error(__('Hubo inconvenientes al eliminar la accesibilidad. Por favor, otra vez intente.'));
                }
                return $this->redirect(['action' => 'index', 'idx' => $TbRecorrido->tb_zabd_id]);
            }
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbRecorrido', $idx]);
        }
    }

    public function exportartabla($idx = null)
    {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT . 'reportes/' . $data['filename'] . '.xlsx';

            if (file_exists($filePath)) {

                $this->response->file($filePath, array('download' => true));

                return $this->response;

            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }


}