<?php

namespace App\Controller\Admin;

use App\Controller\Admin\AppController;
use Cake\Datasource\ConnectionManager;
use Authentication\IdentityInterface;
use Cake\ORM\Entity;

/**
 * TbTramiteDocumentario Controller
 *
 * @property \App\Model\Table\TbTramiteDocumentarioTable $TbTramiteDocumentario
 *
 * @method \App\Model\Entity\TbTramiteDocumentario[] paginate($object = null, array $settings = [])
 */
class TbTramiteDocumentarioController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_modulo = "zona de agrobiodiversidad";
        $this->mod_title = "trámite documentario";
        $this->loadModel('Zabd');
        $this->loadModel('TbTipoDocumento');
        $this->loadModel('OptionList');

        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' => 'Zabd'])->first();
        if (!empty($this->module))
            $this->permiso = $this->Functions->validarModulo($this->module->id);
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */

    public function index($idx = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['index']) {
            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $permiso = $this->permiso;
            $styles = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
            $scripts = [
                'assets/js/select2/select2',
                'assets/js/datatable/jquery.dataTables.min',
                'assets/js/datatable/dataTables.bootstrap.min',
                'assets/js/datatable/dataTables.select.min'
            ];
            // faltaria agregar el status
            $TbTramiteDocumentario = $this->TbTramiteDocumentario->find()->contain(['TbTipoDocumento', 'Zabd'])->where(['tb_zabd_id' => $Zabd->id, 'TbTramiteDocumentario.status' => 1])->all();
            // var_dump($TbTramiteDocumentario); exit;
            if ($TbTramiteDocumentario != NULL) {
                $this->set(compact('TbTramiteDocumentario', 'Zabd', 'mod_modulo', 'mod_title', 'styles', 'scripts', 'permiso'));
                $this->set('_serialize', ['TbTramiteDocumentario']);
            } else {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'Zabd']);
            }
        } else {
            $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index', 'controller' => 'Zabd']);
        }
    }

    public function tipo_documento($idx = null)
    {
        $id_zabd = $idx;
        if ($this->permiso['add']) {
            $TbTipoDocumento = $this->TbTipoDocumento->newEntity();
            if ($this->request->is('post')) {

                $data = $this->request->getData();
                $data['user_id'] = $this->Auth->User('id');
                $data['tipo_documento'] = strtoupper($data['tipo_documento']);
                $TbTipoDocumento = $this->TbTipoDocumento->patchEntity($TbTipoDocumento, $data);
                if ($this->TbTipoDocumento->save($TbTipoDocumento)) {
                    $list_module = explode('/', $this->request->params['_matchedRoute']);
                    $user_id = $this->Auth->User('id');
                    $module = $list_module[(count($list_module) - 2)];
                    $action = $list_module[(count($list_module) - 1)];
                    $station_id = $TbTipoDocumento->id;
                    $recurso_id = '4';
                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                    $this->Flash->success(__('tipo de documento creado satisfactoriamente.'));
                    // return $this->redirect(['action' => 'add', 'controller' => 'TbTipoDocumento', 'idx' => $id_zabd]);
                    // var_dump($id_zabd); exit;
                    // ->redirect(['action' => 'edit', 'controller' => 'TbTramiteDocumentario', 'idx' => $id_zabd]);
                    // return $this->redirect(['action' => 'index', 'id' => $especie->id]);
                }else{
                    $this->Flash->error(__('Hubo inconvenientes al crear tipo de documento. Por favor, otra vez intente.'));

                }
            }

            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];
            $this->set(compact('TbTipoDocumento', 'id_zabd', 'mod_modulo', 'mod_title', 'scripts'));
            // var_dump($TbTipoDocumento); exit();

            $this->set('_serialize', ['TbTipoDocumento']);
        } else {
            $this->Flash->error(__('Operación denegada.'));
            // return $this->redirect(['action' => 'index', 'controller' => 'TbTipoDocumento']);

        }
    }
    /**
     * View method
     *
     * @param string|null $id Zabd Accesion id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($idx = null, $id = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['view']) {
            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $permiso = $this->permiso;
            $TbTramiteDocumentario = $this->TbTramiteDocumentario->find()->contain(['TbTipoDocumento', 'Zabd'])
                ->where(['TbTramiteDocumentario.id' => $id, 'TbTramiteDocumentario.tb_zabd_id' => $idx, 'TbTramiteDocumentario.status' => '1'])
                ->first();
            if ($TbTramiteDocumentario != NULL) {
                $this->set(compact('TbTramiteDocumentario', 'mod_modulo', 'mod_title', 'permiso', 'Zabd'));
                $this->set('_serialize', ['TbTramiteDocumentario']);
            } else {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'TbTramiteDocumentario', $idx]);
            }
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbTramiteDocumentario', $idx]);
        }
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($idx = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['add']) {
            $TbTramiteDocumentario = $this->TbTramiteDocumentario->newEntity();
            if ($this->request->is('post')) {
                $data = $this->request->getData();
                if ($data['fecha_salidas'] != '' && date('Y-m-d', strtotime($data['fecha_salidas'])) <= date("Y-m-d",strtotime(date('Y-m-d')))) {
                    $data['fecha_salida'] = date('Y-m-d', strtotime($data['fecha_salidas']));
                } else {
                    $data['fecha_salida'] = '';
                }

                if ($data['fecha_ingresos'] != '' && $data['fecha_ingresos'] <= date('d-m-Y')) {
                    $data['fecha_ingreso'] = date('Y-m-d', strtotime($data['fecha_ingresos']));
                } else {
                    $data['fecha_ingreso'] = '';
                }

                $data['tb_zabd_id'] = $Zabd->id;
                $TbTramiteDocumentario = $this->TbTramiteDocumentario->patchEntity($TbTramiteDocumentario, $data);
                if ($this->TbTramiteDocumentario->save($TbTramiteDocumentario)) {
                    $list_module = explode('/', $this->request->params['_matchedRoute']);
                    $user_id = $this->Auth->User('id');
                    $module = $list_module[(count($list_module) - 2)];
                    $action = $list_module[(count($list_module) - 1)];
                    $station_id = $TbTramiteDocumentario->id;
                    $recurso_id = '4';
                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                    $this->Flash->success(__('tramite documentario creado satisfactoriamente.'));
                    return $this->redirect(['action' => 'index', 'controller' => 'TbTramiteDocumentario', $idx]);
                    // var_dump("Nada por mostrar");
                    // exit;
                }



                $this->Flash->error(__('Hubo inconvenientes al crear el tramite documentario. Por favor, otra vez intente.'));
            }

            $mod_modulo = $this->mod_modulo;
            $mod_title = $this->mod_title;
            $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];
            $TbTipoDocumento = $this->TbTramiteDocumentario->TbTipoDocumento->find('list', ['keyField' => 'id', 'valueField' => 'tipo_documento'])->where(['TbTipoDocumento.status' => '1']);
            $TbTramiteDocumentario->fecha_ingreso = ($TbTramiteDocumentario->fecha_ingreso == NULL) ? NULL : date('d-m-Y', strtotime($TbTramiteDocumentario->fecha_ingreso));
            $TbTramiteDocumentario->fecha_salida = ($TbTramiteDocumentario->fecha_salida == NULL) ? NULL : date('d-m-Y', strtotime($TbTramiteDocumentario->fecha_salida));
            $this->set(compact('TbTramiteDocumentario', 'mod_modulo', 'mod_title', 'TbTipoDocumento', 'Zabd'));
            $this->set('_serialize', ['TbTramiteDocumentario']);
        } else {
            // var_dump("Know"); exit;
            return $this->redirect(['action' => 'index', 'controller' => 'TbTramiteDocumentario', $idx]);
        }
    }

    /**
     *
     * @param string|null $id Zabd Accesion id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($idx = null, $id = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['edit']) {
            $TbTramiteDocumentario = $this->TbTramiteDocumentario->find()->where(['TbTramiteDocumentario.id' => $id, 'TbTramiteDocumentario.status' => '1', 'tb_zabd_id' => $idx])->first();
            if ($TbTramiteDocumentario != NULL) {
                if ($this->request->is(['putch', 'post', 'put'])) {
                    $data = $this->request->getData();
                if ($data['fecha_salidas'] != '' && date('Y-m-d', strtotime($data['fecha_salidas'])) <= date("Y-m-d",strtotime(date('Y-m-d')))) {
                        $data['fecha_salida'] = date('Y-m-d', strtotime($data['fecha_salidas']));
                    } else {
                        $data['fecha_salida'] = '';
                    }

                    if ($data['fecha_ingresos'] != '' && $data['fecha_ingresos'] <= date('d-m-Y')) {
                        $data['fecha_ingreso'] = date('Y-m-d', strtotime($data['fecha_ingresos']));
                    } else {
                        $data['fecha_ingreso'] = '';
                    }
                    // if ($data['fecha_salidas'] != '' && $data['fecha_ingresos'] != '' && $data['fecha_salidas'] <= date('d-m-Y') && $data['fecha_ingresos'] <= date('d-m-Y') && $data['fecha_salidas'] <= $data['fecha_ingresos']) {
                    //     $data['fecha_salida'] = date('Y-m-d', strtotime($data['fecha_salidas']));
                    //     $data['fecha_ingreso'] = date('Y-m-d', strtotime($data['fecha_ingresos']));
                    // } else {
                    //     $data['fecha_salida'] = '';
                    //     $data['fecha_ingreso'] = '';
                    // }
                    $data['tb_zabd_id'] = $Zabd->id;
                    $TbTramiteDocumentario = $this->TbTramiteDocumentario->patchEntity($TbTramiteDocumentario, $data);
                    if ($this->TbTramiteDocumentario->save($TbTramiteDocumentario)) {
                        $list_module = explode('/', $this->request->params['_matchedRoute']);
                        $user_id = $this->Auth->User('id');
                        $module = $list_module[(count($list_module) - 2)];
                        $action = $list_module[(count($list_module) - 1)];
                        $station_id = $TbTramiteDocumentario->id;
                        $recurso_id = '4';
                        $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                        $this->Flash->success(__('tramite documentario creado satisfactoriamente.'));
                        return $this->redirect(['action' => 'index', 'idx' => $Zabd->id]);
                    }
                    $this->Flash->error(__('Hubo inconvenientes al crear el tramite documentario. Por favor, otra vez intente.'));
                }
                $mod_modulo = $this->mod_modulo;
                $mod_title = $this->mod_title;
                $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];
                $TbTipoDocumento = $this->TbTramiteDocumentario->TbTipoDocumento->find('list', ['keyField' => 'id', 'valueField' => 'tipo_documento'])->where(['TbTipoDocumento.status' => '1']);
                $this->set(compact('TbTramiteDocumentario', 'mod_modulo', 'mod_title', 'TbTipoDocumento', 'Zabd'));
                $TbTramiteDocumentario->fecha_ingreso = ($TbTramiteDocumentario->fecha_ingreso == NULL) ? NULL : date('d-m-Y', strtotime($TbTramiteDocumentario->fecha_ingreso));
                $TbTramiteDocumentario->fecha_salida = ($TbTramiteDocumentario->fecha_salida == NULL) ? NULL : date('d-m-Y', strtotime($TbTramiteDocumentario->fecha_salida));
                $this->set('_serialize', ['TbTramiteDocumentario']);
            }
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbTramiteDocumentario', $idx]);
        }
    }

    /**
     * Delete method
     *
     * @param string|null $id Zabd Accesion id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($idx = null, $id = null)
    {
        $Zabd = $this->Zabd->find()->where(['Zabd.id' => $idx, 'Zabd.status' => '1'])->first();
        if ($Zabd != NULL && $this->permiso['delete']) {
            $this->request->is(['post', 'delete']);
            $TbTramiteDocumentario = $this->TbTramiteDocumentario->find()->where(['TbTramiteDocumentario.id' => $id, 'TbTramiteDocumentario.status' => '1', 'tb_zabd_id' => $idx])->first();
            if ($TbTramiteDocumentario == NULL) {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index', 'controller' => 'TbTramiteDocumentario', $idx]);
            } else {
                $TbTramiteDocumentario['status'] = 0;
                if ($this->TbTramiteDocumentario->save($TbTramiteDocumentario)) {
                    $list_module = explode('/', $this->request->params['_matchedRoute']);
                    $user_id = $this->Auth->User('id');
                    $module = $list_module[(count($list_module) - 3)];
                    $action = $list_module[(count($list_module) - 2)];
                    $station_id = $TbTramiteDocumentario->id;
                    $recurso_id = '4';
                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                    $this->Flash->success(__('tramite documentario eliminada satisfactoriamente.'));
                } else {
                    $this->Flash->error(__('Hubo inconvenientes al eliminar la tramite documentario. Por favor, otra vez intente.'));
                }
                return $this->redirect(['action' => 'index', 'idx' => $TbTramiteDocumentario->tb_zabd_id]);
            }
        } else {
            return $this->redirect(['action' => 'index', 'controller' => 'TbTramiteDocumentario', $idx]);
        }
    }

    public function exportartabla($idx = null)
    {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT . 'reportes/' . $data['filename'] . '.xlsx';

            if (file_exists($filePath)) {

                $this->response->file($filePath, array('download' => true));

                return $this->response;
            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }
}
